### ISSUE TITLE
Delete build-all shell script - MPF should be built using Ant

### ISSUE THREAD

**Issue by ampf** [ampf/AMPF#1]
The shell script is causing confusion.

**Comment by gbowles** [comment]
Removed build-all shell script: Closed by f57c3601f09c81334fde1b6cf026513effec452e

**Comment by simontuffs** [comment]
This will break the build, since ant build.xml delegates building the MPF C components to build-all.sh.   Maybe rename it to a hidden file (.build-all), then it can still be invoked from the command shell (e.g. to install on the system, which this script does do, without doing an RPM).  Maybe remove that stage, I don't use it, and the RPM build workflow is more appropriate.

**Comment by wstidolph** [comment]
It does indeed break the build ... but rather than having a hidden file I'd rather just a different name: "shell-build-all" or something

**Comment by simontuffs** [comment]
How about build-components.sh (non executable).  True it builds data-types and tools too, but we can ignore that.

**Comment by ampf** [comment]
Put back as build-components.sh and changed build.xml accordingly; need to check the file permissions.

**Comment by simontuffs** [comment]
Everything working now.
